# Generated by Django 3.1.7 on 2021-05-15 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACHCheckDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pick_payer_logo', models.ImageField(upload_to='signature_pic/')),
                ('is_active', models.BooleanField(default=True)),
                ('check_number', models.CharField(max_length=256)),
                ('receiver_name', models.CharField(blank=True, max_length=20, null=True)),
                ('check_type', models.CharField(default='Headless', max_length=20)),
                ('sender_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('receiver_mail', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('memo', models.CharField(blank=True, max_length=256, null=True)),
                ('paid_amount', models.FloatField()),
                ('currency_type', models.CharField(default='USD', max_length=26)),
                ('check_token', models.CharField(max_length=256)),
                ('sender_name', models.CharField(default='', max_length=256)),
                ('check_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('valid_upto', models.DateField()),
                ('signature_pic', models.ImageField(upload_to='signature_pic/')),
                ('bank_logo', models.ImageField(upload_to='bank_logo/')),
                ('amount_in_words', models.CharField(blank=True, max_length=256, null=True)),
                ('pay_to_the_order', models.CharField(blank=True, max_length=256, null=True)),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='back_image/')),
                ('frontend_image', models.ImageField(blank=True, null=True, upload_to='front_image/')),
            ],
        ),
    ]
