# Generated by Django 3.1.7 on 2021-05-20 14:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0003_testedcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierCheckDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pick_payer_logo', models.ImageField(upload_to='signature_pic/')),
                ('is_active', models.BooleanField(default=True)),
                ('check_number', models.CharField(max_length=256)),
                ('receiver_name', models.CharField(blank=True, max_length=20, null=True)),
                ('check_type', models.CharField(default='Headless', max_length=20)),
                ('sender_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('receiver_mail', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('memo', models.CharField(blank=True, max_length=256, null=True)),
                ('paid_amount', models.FloatField()),
                ('currency_type', models.CharField(default='USD', max_length=26)),
                ('check_token', models.CharField(max_length=256)),
                ('sender_name', models.CharField(default='', max_length=256)),
                ('check_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('valid_upto', models.DateField()),
                ('signature_pic', models.ImageField(upload_to='signature_pic/')),
                ('bank_logo', models.ImageField(upload_to='bank_logo/')),
                ('amount_in_words', models.CharField(blank=True, max_length=256, null=True)),
                ('pay_to_the_order', models.CharField(blank=True, max_length=256, null=True)),
                ('check_image', models.ImageField(blank=True, null=True, upload_to='back_image/')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('receiver_name', models.CharField(blank=True, max_length=20, null=True)),
                ('sender_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('receiver_mail', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('check_token', models.CharField(max_length=256)),
                ('sender_name', models.CharField(default='', max_length=256)),
                ('money_order_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('pay_to_the_order', models.CharField(blank=True, max_length=256, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('otp_token', models.CharField(blank=True, max_length=15, null=True)),
                ('activation_token', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ACHCheckDetail',
        ),
        migrations.AlterField(
            model_name='testedcheck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='check_valid/'),
        ),
    ]
