# Generated by Django 3.1.7 on 2021-05-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20210523_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiercheckdetail',
            name='account_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cashiercheckdetail',
            name='routing_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cashiercheckdetail',
            name='check_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
