# Generated by Django 3.1.7 on 2021-05-23 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20210523_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiercheckdetail',
            name='number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cashiercheckdetail',
            name='check_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
