# Generated by Django 3.1.7 on 2021-05-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_auto_20210524_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyorder',
            name='money_order_photo',
            field=models.ImageField(blank=True, null=True, upload_to='money_order_image/'),
        ),
        migrations.AlterField(
            model_name='moneyorder',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='money_qrs/'),
        ),
    ]
