# Generated by Django 3.1.7 on 2021-05-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_datasetsachmerchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetsachmerchant',
            name='is_requested_payment',
        ),
    ]
