# Generated by Django 3.1.7 on 2021-05-29 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_datasetsachmerchant_is_requested_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetsachmerchant',
            name='user_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_data', to='wallet.pay2mateuser'),
        ),
    ]
